# Generated by Django 4.2.1 on 2023-05-06 01:26

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='idade',
            field=models.IntegerField(null=True, blank=True),
        ),
    ]
